# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('buffer-and-switch', ['core', 'network', 'internet', 'mobility', 'applications', 'wifi'])
    module.source = [
        'model/bs-routing.cc',
	'model/bs-routing-table.cc',
	'model/bs-routing-packet.cc',
        'helper/bs-routing-helper.cc',
        ]

    #module_test = bld.create_ns3_module_test_library('buffer-and-switch')
    #module_test.source = [
    #    'test/buffer-and-switch-test-suite.cc',
    #    ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'buffer-and-switch'
    headers.source = [
        'model/bs-routing.h',
        'model/bs-routing-table.h',
        'model/bs-routing-packet.h',
        'helper/bs-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    bld.ns3_python_bindings()

